### PR TITLE
fix the border radius

### LINKED ISSUE #155: advanced tab breaks border when expanded
## What happened?

It appears that the outside panel of the advanced tab is broken. 

Screen Shot 2022-08-04 at 9 12 16 AM

When collapsed, it looks fine

Screen Shot 2022-08-04 at 9 13 34 AM

## What did you expect to happen?

Advanced pane to be properly bordered. 

## What's your environment like?

- Pomerium Desktop version: Desktop Version: 0.18.0-a8ffe1e , CLI Version: v0.18.0
- Server Operating System/Architecture/Cloud: MacOs Monterey 12.5 (21G72)

## Config export

N/A

### PR DESCRIPTION
**Pull request by nhayfield**
## Summary
Fix the border radius which is a string now in newer versions of MUI

## Related issues
Fixes #155 

## Checklist

- [x] reference any related issues
- [ ] updated docs
- [ ] updated unit tests
- [ ] updated UPGRADING.md
- [x] add appropriate tag (`improvement` / `bug` / etc)
- [x] ready for review

### CODE REVIEW

File: src/renderer/pages/ConnectForm.tsx [hunk 1]
```diff
@@ -341,7 +341,7 @@ const ConnectForm: FC<Props> = () => {
             marginTop: 2,
             paddingLeft: 2,
             paddingRight: 2,
-            borderRadius: 16,
+            borderRadius: '16px',
```
Comment (desimone) [inline src/renderer/pages/ConnectForm.tsx:344]: Are the other padding values broken, or just borderRadius?
